### ISSUE TITLE
碰到的问题?

### ISSUE THREAD

**Issue by attachmentList** [fengahan/Yat#4]
![image](https://user-images.githubusercontent.com/28923762/58086037-6ba73b00-7bf0-11e9-9f08-5843867ad70c.png)

加个搜索比较好.

![image](https://user-images.githubusercontent.com/28923762/58086173-b45ef400-7bf0-11e9-9fa4-00239cdcb919.png)

没做去重应该 , 而且 /route/* 这种路由添加不成功.

管理员头像上传之后,一样没有.

编辑管理员 角色跟权限这一栏有时会报错.

**Comment by fengahan** [comment]
麻烦请详细告诉我上面的截图来源 以及按照条目明确的告诉我问题。以及 编辑管理员 角色跟权限具体的报错信息
